"""
SAJHA MCP Server - saad_fib Tool v2.9.8

Copyright © 2025-2030, All Rights Reserved
Generated by MCP Studio

Description: Calculate the factorial of a number
Category: Mathematics
Author: MCP Studio User
"""

from typing import Dict, Any, List, Optional
from sajha.tools.base_mcp_tool import BaseMCPTool


class SaadFibTool(BaseMCPTool):
    """
    Calculate the factorial of a number
    
    Generated by MCP Studio from @sajhamcptool decorated function.
    """
    
    def __init__(self, config: Dict = None):
        """Initialize saad_fib tool."""
        default_config = {
            'name': 'saad_fib',
            'description': 'Calculate the factorial of a number',
            'version': '2.9.8',
            'enabled': True
        }
        if config:
            default_config.update(config)
        super().__init__(default_config)
    
    def get_input_schema(self) -> Dict:
        """Define the input schema for this tool."""
        return {
        "type": "object",
        "properties": {
                "n": {
                        "type": "integer"
                }
        },
        "required": [
                "n"
        ]
}
    
    def get_output_schema(self) -> Dict:
        """Define the output schema for this tool."""
        return {
        "type": "object",
        "description": "Result from calculate_factorial"
}
    
    def execute(self, arguments: Dict[str, Any]) -> Dict:
        """
        Execute the tool with provided arguments.
        
        Args:
            arguments: Dictionary of input arguments
            
        Returns:
            Tool execution result
        """
        # Extract arguments
        n = arguments['n']

        if n < 0:
            return {"error": "Factorial not defined for negative numbers"}

        result = 1
        for i in range(1, n + 1):
            result *= i

        return {
            "input": n,
            "factorial": result
        }


# Tool registry entry
SAAD_FIB_TOOLS = {
    'saad_fib': SaadFibTool
}