"""initial_schema

Revision ID: 50eb8a9c07d5
Revises: 
Create Date: 2026-04-11 17:01:27.361633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50eb8a9c07d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('event_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('thread_id', sa.String(length=64), nullable=True),
    sa.Column('tool_name', sa.String(length=128), nullable=True),
    sa.Column('tool_result_ok', sa.Boolean(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('file_section', sa.String(length=64), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_audit_tool', 'audit_events', ['tool_name', 'created_at'], unique=False)
    op.create_index('idx_audit_type', 'audit_events', ['event_type', 'created_at'], unique=False)
    op.create_index('idx_audit_user', 'audit_events', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_audit_worker', 'audit_events', ['worker_id', 'created_at'], unique=False)
    op.create_table('connectors',
    sa.Column('connector_type', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('credentials_enc', sa.LargeBinary(), nullable=True),
    sa.Column('credentials_iv', sa.LargeBinary(), nullable=True),
    sa.Column('has_credentials', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('connector_type')
    )
    op.create_table('file_metadata',
    sa.Column('file_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('section', sa.String(length=64), nullable=False),
    sa.Column('s3_key', sa.Text(), nullable=False),
    sa.Column('rel_path', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('is_folder', sa.Boolean(), nullable=False),
    sa.Column('bm25_indexed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index('idx_file_meta_search', 'file_metadata', ['worker_id', 'file_name'], unique=False)
    op.create_index('idx_file_meta_tree', 'file_metadata', ['worker_id', 'section', 'rel_path'], unique=False)
    op.create_table('flask_sessions',
    sa.Column('session_id', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('idx_sessions_expires', 'flask_sessions', ['expires_at'], unique=False)
    op.create_table('workers',
    sa.Column('worker_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('enabled_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('domain_data_path', sa.String(length=512), nullable=True),
    sa.Column('verified_wf_path', sa.String(length=512), nullable=True),
    sa.Column('connector_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_index('idx_users_worker_id', 'users', ['worker_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('key_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('key_id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('conversation_threads',
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('worker_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('token_count_est', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.create_index('idx_threads_active', 'conversation_threads', ['user_id', 'archived_at'], unique=False)
    op.create_index('idx_threads_user_worker', 'conversation_threads', ['user_id', 'worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_threads_user_worker', table_name='conversation_threads')
    op.drop_index('idx_threads_active', table_name='conversation_threads')
    op.drop_table('conversation_threads')
    op.drop_table('api_keys')
    op.drop_index('idx_users_worker_id', table_name='users')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_table('users')
    op.drop_table('workers')
    op.drop_index('idx_sessions_expires', table_name='flask_sessions')
    op.drop_table('flask_sessions')
    op.drop_index('idx_file_meta_tree', table_name='file_metadata')
    op.drop_index('idx_file_meta_search', table_name='file_metadata')
    op.drop_table('file_metadata')
    op.drop_table('connectors')
    op.drop_index('idx_audit_worker', table_name='audit_events')
    op.drop_index('idx_audit_user', table_name='audit_events')
    op.drop_index('idx_audit_type', table_name='audit_events')
    op.drop_index('idx_audit_tool', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
